name: 'Tagging Strategy'
description: 'Easy Tag creating for docker tagging strategies'
inputs:
  pattern:
    description: 'The tagging strategy for this run'
    required: true
    default: 'X.Y.Z'
  tag_name:
    description: 'The string to parse'
    required: true
outputs:
  strategy_tag:
    description: 'Outputs a tag based on the the strategy for this run'
runs:
  using: 'node12'
  main: 'dist/index.js'
