name: Debug

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tagging Strategy
      id: tagging
      uses: ./
      with:
        pattern: 'X.Y.Z'
    - name: Check Output
      id: debug_log
      run: echo "The resulting tag is ${{ steps.tagging.outputs.strategy_tag }}"
