name: Debug

on: 
  push:
    branches:
      - debug

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tagging Strategy
      id: tagging
      uses: ./
      with:
        tag_name: ${{ github.ref }}
        pattern: '%X.Y.Z%'
    - name: Check Output
      id: debug_log
      run: echo "The resulting tag is ${{ steps.tagging.outputs.tag }}"
