name: Test

on:
  repository_dispatch:
    types: [release]
  push:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tags w/latest
        id: tags-latest
        uses: ./
        with:
          latest: true
          tags: |
            %x%
            %X.Y%
            %X.Y.Z%
          image_name: hello/world
          tag_name: 1.0.0rc1
      - name: Use latest Tags
        run: echo ${{ steps.tags-latest.outputs.tags }}
      - name: Tags w/o latest
        id: tags-wo-latest
        uses: ./
        with:
          latest: false
          tags: |
            %x%
            %X.Y%
            %X.Y.Z%
          image_name: hello/world
          tag_name: 1.0.0rc1
      - name: Use Tags w/o latest
        run: echo ${{ steps.tags-wo-latest.outputs.tags }}
