name: Release Dispatch

on:
  repository_dispatch:
    types: [release]

jobs:
  debug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-tagging-strategy: ['%X%-foobar', '%X.Y%-foobar', '%X.Y.Z%-foobar']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tagging
        id: tagging
        uses: ./
        with:
          pattern: ${{ matrix.image-tagging-strategy }}
          tag_name: ${{ github.event.client_payload.tag_name }}
      - name: Use Tag
        run: echo ${{ steps.tagging.outputs.tag }}
